:rootdir: .
:icons: font
:imagesdir: {rootdir}/images

ifdef::env-github,env-browser[:badges:]
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

ifndef::badges[]
= Emerald-rs
endif::[]

ifdef::badges[]
= Emerald-rs image:https://img.shields.io/travis/ethereumproject/emerald-rs/master.svg?style=flat-square["Build Status", link="https://travis-ci.org/ethereumproject/emerald-rs"] image:https://img.shields.io/appveyor/ci/dulanov/emerald-rs/master.svg?style=flat-square["Build Status", link="https://ci.appveyor.com/project/dulanov/emerald-rs"] image:https://img.shields.io/badge/License-Apache%202.0-blue.svg?style=flat-square&maxAge=2592000["License", link="https://github.com/ethereumproject/emerald-rs/blob/master/LICENSE"]
endif::[]

Ethereum Classic offline wallet written in Rust.

Distributed as a command line tool (CLI), as a Rust crate or you can use it in the form of plain C library.

If you are looking for for a full-featured UI wallet, take a look at our link:https://github.com/ethereumproject/emerald-wallet[Ethereum Classic Emerald Wallet].

Developed by link:http://www.etcdevteam.com/[ETCDEV Team].

== Features

=== General

* [x] Accounts
* [x] Transactions signing
* [ ] Smart contracts (ABI)
* [ ] C interface (ABI)

== Installation

Ensure you have these dependencies installed:

----
openssl gcc pkgconfig
----

Also ensure that your installation of cargo (version 0.18) and rustc (version 1.17) is up to date.

If your distribution or operating system does not have recent cargo and rustc binaries you can install them from: http://doc.crates.io/

----
$ git clone https://github.com/ethereumproject/emerald-rs
----

== Usage

How to run emerald connector (by default on port '1920'):

----
$ RUST_LOG=emerald,rpc cargo run
----

For more details look at link:./usage.txt[usage].

== Examples

----
extern crate emerald;

use std::net::SocketAddr;

fn main() {
    let addr = "127.0.0.1:1920"
        .parse::<SocketAddr>()
        .expect("Expect to parse address");

    emerald::start(&addr, None, None);
}
----

For more see link:./examples[examples folder].

== References

=== <<docs/api.adoc#,JSON RPC API>>

== License

Apache 2.0
