:rootdir: .
:icons: font
:imagesdir: {rootdir}/images

ifdef::env-github,env-browser[:badges:]
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

ifndef::badges[]
= Emerald-rs
endif::[]

ifdef::badges[]
= Emerald-rs image:https://img.shields.io/travis/ethereumproject/emerald-rs/master.svg?style=flat-square["Build Status", link="https://travis-ci.org/ethereumproject/emerald-rs"] image:https://img.shields.io/appveyor/ci/dulanov/emerald-rs/master.svg?style=flat-square["Build Status", link="https://ci.appveyor.com/project/dulanov/emerald-rs"] image:https://img.shields.io/codecov/c/github/ethereumproject/emerald-rs/master.svg?style=flat-square[Codecov, link=https://codecov.io/gh/ethereumproject/emerald-rs] image:https://img.shields.io/badge/License-Apache%202.0-blue.svg?style=flat-square&maxAge=2592000["License", link="https://github.com/ethereumproject/emerald-rs/blob/master/LICENSE"]
endif::[]

Ethereum classic web3 like connector written in Rust.

Distributed as a command line tool (CLI), as a Rust crate or you can use it in the form of plain C library.

As a reference dApp implementation take a look at our link:https://github.com/ethereumproject/emerald-wallet[Ethereum Classic Emerald Wallet].

Developed by link:http://www.etcdevteam.com/[ETCDEV Team].

== Features

=== General

* [ ] Accounts (In Progress)
* [ ] Address books
* [ ] Transactions signing
* [ ] C interface (ABI)

=== Transport

* [ ] IPC
* [ ] HTTP (In Progress)
* [ ] WebSockets

== Roadmap

=== MVP (Mar'17, In Progress)

Basic version with minimal features for developers just to build and run on local machine.

=== Internal Beta (Apr'17)

Internal version with general features for testing and for early DApp adopters.

=== Public Beta (May'17)

First public release.

=== Prerequisites

Ensure you have these dependencies installed:

----
openssl gcc pkgconfig libudev
----

We recommend to use parity as ethereum classic node:

----
$ cargo install --git https://github.com/ethcore/parity.git --branch stable --force parity
----

How to run parity locally in development mode (v1.5+) on port '8545' (by default):

----
$ parity --chain dev --no-discovery --no-ui --no-ipc --no-dapps --rpccorsdomain "*" --jsonrpc-apis "web3,eth,net,personal,parity,parity_set,traces,rpc,parity_accounts"
----

== Installation

Ensure you have these dependencies installed:

----
openssl gcc pkgconfig
----

----
$ git clone https://github.com/ethereumproject/emerald-rs
----

=== Usage

How to run emerald connector (on port '1920' by default) on top of ethereum classic node:

----
$ RUST_LOG=emerald,rpc cargo run
----

For more details look at link:./usage.txt[usage].

=== Examples

TBD, just a first design prototype:

----
extern crate emerald;

use emerald::Client
use emerald::transport::Http;

fn main() {
  let etc = Client::new(Http::new("http://localhost:8545").unwrap());

  println!("Accounts: {:?}", etc.eth().accounts().unwrap());
}
----

For more see link:./examples[examples folder].

== License

Apache 2.0
