:rootdir: .
:icons: font
:imagesdir: {rootdir}/images

ifdef::env-github,env-browser[:badges:]
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

ifndef::badges[]
= Emerald-rs
endif::[]

ifdef::badges[]
= Emerald-rs image:https://img.shields.io/travis/ethereumproject/emerald-rs/master.svg?style=flat-square["Build Status", link="https://travis-ci.org/ethereumproject/emerald-rs"] image:https://img.shields.io/appveyor/ci/dulanov/emerald-rs/master.svg?style=flat-square["Build Status", link="https://ci.appveyor.com/project/dulanov/emerald-rs"] image:https://img.shields.io/badge/License-Apache%202.0-blue.svg?style=flat-square&maxAge=2592000["License", link="https://github.com/ethereumproject/emerald-rs/blob/master/LICENSE"]
endif::[]

Ethereum classic web3 like connector written in Rust.

Distributed as a command line tool (CLI), as a Rust crate or you can use it in the form of plain C library.

As a reference dApp implementation take a look at our link:https://github.com/ethereumproject/emerald-wallet[Ethereum Classic Emerald Wallet].

Developed by link:http://www.etcdevteam.com/[ETCDEV Team].

== Features

=== General

* [x] Accounts
* [x] Address books
* [x] Transactions signing
* [ ] C interface (ABI)

=== Transport

* [ ] IPC
* [x] HTTP

== Roadmap

=== Internal Beta (May'17, In Progress)

Internal version with general features for testing and for early dApp adopters, to use only in testnet.

=== Public Beta (July'17)

First public release.

== Installation

Ensure you have these dependencies installed:

----
openssl gcc pkgconfig
----

----
$ git clone https://github.com/ethereumproject/emerald-rs
----

=== Usage

How to run emerald connector (on port '1920' by default) on top of ethereum classic node (we recommend link:https://github.com/ethereumproject/go-ethereum[Geth]):

----
$ RUST_LOG=emerald,rpc cargo run
----

For more details look at link:./usage.txt[usage].

=== Examples

----
extern crate emerald;

use std::net::SocketAddr;

fn main() {
    let addr = "127.0.0.1:1920"
        .parse::<SocketAddr>()
        .expect("Expect to parse address");

    let client_addr = "127.0.0.1:8545"
        .parse::<SocketAddr>()
        .expect("Expect to parse client address");

    emerald::start(&addr, &client_addr, None);
}
----

For more see link:./examples[examples folder].

== License

Apache 2.0
