ifdef::env-github,env-browser[:outfilesuffix: .adoc]
ifndef::rootdir[:rootdir: ..]
:imagesdir: {rootdir}/images
:toc:

= JSON-RPC API

JSON-RPC is a remote procedure call protocol encoded in JSON.
We use the http://www.jsonrpc.org/specification[version 2 of the protocol].

== Methods

=== emerald_heartbeat

Identify if and when the originator fails or is no longer available.

*Parameters*: none

*Result*: `timestamp` (Number) - seconds since Jan 01 1970 (UTC)

*Examples*:

----
--> {"jsonrpc": "2.0", "method": "emerald_heartbeat", "params": [], "id": 1}
<-- {"jsonrpc": "2.0", "result": 1497439590, "id": 1}
----

=== emerald_currentVersion

Returns the client current version.

*Parameters*: none

*Result*: `version` (String) - current version according http://semver.org/[Semantic Versioning]

*Examples*:

----
--> {"jsonrpc": "2.0", "method": "emerald_currentVersion", "params": [], "id": 1}
<-- {"jsonrpc": "2.0", "result": "0.9", "id": 1}
----

=== emerald_listAccounts

Return the list of all not hidden accounts from the keystore.

*Parameters*:

    * `additional` (Object, optional)
    ** `chain` (String, optional) - chain name, by default `mainnet`, other possible variant `testnet`
    ** `chain_id` (Number, optional) - chain id number, by default for `mainnet` it equals `61`
    ** `show_hidden` (Boolean, optional) - also show hidden accounts

*Result*:

    * `accounts` (Array)
    ** `account` (Object) - an account
    *** `name` (String, optional) - account name
    *** `description` (String, optional) - account description
    *** `address` (String) - hex-encoded 20 bytes public address

*Examples*:

----
--> {"jsonrpc": "2.0", "method": "emerald_listAccounts", "params": [{"chain": "testnet"}], "id": 1}
<-- {"jsonrpc": "2.0", "result":
      [{"address": "0x5e97870f263700f46aa00d967821199b9bc5a120"},
       {"name": "main",
        "address": "0x3d80b31a78c30fc628f20b2c89d7ddbf6e53cedc"}],
       {"name": "test",
        "description": "A test account",
        "address": "0xe9a7e26bf5c05fe3bae272d4c940bd7158611ce9"}],
     "id": 1}
----

=== emerald_hideAccount

Hide an account from the list returned by `emerald_listAccounts`.

*Parameters*:

    * `account` (Object)
    ** `address` (String) - hex-encoded 20 bytes public address
    * `additional` (Object, optional)
    ** `chain` (String, optional) - chain name, by default `mainnet`, other possible variant `testnet`
    ** `chain_id` (Number, optional) - chain id number, by default for `mainnet` it equals `61`

*Result*: `accept` (Boolean) - `true` if required account exists

*Examples*:

.If required account exists
----
--> {"jsonrpc": "2.0", "method": "emerald_hideAccount", "params": [{"address": "0xe9a7e26bf5c05fe3bae272d4c940bd7158611ce9"}], "id": 1}
<-- {"jsonrpc": "2.0", "result": true, "id": 1}
----

.If required account doesn't exist
----
--> {"jsonrpc": "2.0", "method": "emerald_hideAccount", "params": [{"address": "0x3d80b31a78c30fc628f20b2c89d7ddbf6e53cedc"}], "id": 1}
<-- {"jsonrpc": "2.0", "error": {"code": -32000, "message": "Account doesn't exist"}, "id": "1"}
----

=== emerald_unhideAccount

Show an account that was hidden before by the command `emerald_hideAccount`.

*Parameters*:

    * `account` (Object)
    ** `address` (String) - hex-encoded 20 bytes public address
    * `additional` (Object, optional)
    ** `chain` (String, optional) - chain name, by default `mainnet`, other possible variant `testnet`
    ** `chain_id` (Number, optional) - chain id number, by default for `mainnet` it equals `61`

*Result*: `accept` (Boolean) - `true` if required account exists

*Examples*:

.If required account exists
----
--> {"jsonrpc": "2.0", "method": "emerald_revealAccount", "params": [{"address": "0xe9a7e26bf5c05fe3bae272d4c940bd7158611ce9"}], "id": 1}
<-- {"jsonrpc": "2.0", "result": true, "id": 1}
----

.If required account doesn't exist
----
--> {"jsonrpc": "2.0", "method": "emerald_revealAccount", "params": [{"address": "0x3d80b31a78c30fc628f20b2c89d7ddbf6e53cedc"}], "id": 1}
<-- {"jsonrpc": "2.0", "error": {"code": -32000, "message": "Account doesn't exist"}, "id": "1"}
----

=== emerald_newAccount

Creates a new account and stores it locally as a passphrase-encoded keystore file.

*Parameters*:

    * `account` (Object)
    ** `name` (String, optional) - account name
    ** `description` (String, optional) - account description
    ** `passphrase` (String) - passphrase used to encode keyfile (recommend to use 8+ words with good entropy)
    * `additional` (Object, optional)
    ** `chain` (String, optional) - chain name, by default `mainnet`, other possible variant `testnet`
    ** `chain_id` (Number, optional) - chain id number, by default for `mainnet` it equals `61`

*Result*: `address` (String) - hex-encoded 20 bytes public address

*Examples*:

.Simple format, only `passphrase`
----
--> {"jsonrpc": "2.0", "method": "emerald_newAccount", "params": [{"passphrase": "1234567890"}], "id": 1}
<-- {"jsonrpc": "2.0", "result": "0xe9a7e26bf5c05fe3bae272d4c940bd7158611ce9", "id": 1}
----

.Full format with all optional parameters for `testnet` (id: `62`)
----
--> {"jsonrpc": "2.0",
     "method": "emerald_newAccount",
     "params":
       [{"name": "test",
         "description": "A test account"
         "passphrase": "1234567890"},
        {"chain": "testnet"}],
     "id": 1}
<-- {"jsonrpc": "2.0", "result": "0xe9a7e26bf5c05fe3bae272d4c940bd7158611ce9", "id": 1}
----

=== emerald_shakeAccount

Recreate account with the same public address, but with a different passphrase.

*Parameters*:

    * `account` (Object)
    ** `address` (String) - hex-encoded 20 bytes public address
    ** `old_passphrase` (String) - old passphrase used to encode keyfile
    ** `new_passphrase` (String) - new passphrase to recreate keyfile (recommend to use 8+ words with good entropy)
    * `additional` (Object, optional)
    ** `chain` (String, optional) - chain name, by default `mainnet`, other possible variant `testnet`
    ** `chain_id` (Number, optional) - chain id number, by default for `mainnet` it equals `61`

*Result*: `accept` (Boolean) - `true` if required account exists

*Examples*:

----
--> {"jsonrpc": "2.0", "method": "emerald_shakeAccount", "params": [{"address": "0xe9a7e26bf5c05fe3bae272d4c940bd7158611ce9", "old_passphrase": "1234567890", "new_passphrase": "123"}], "id": 1}
<-- {"jsonrpc": "2.0", "result": true, "id": 1}
----

=== emerald_updateAccount

Update not secured by passphrase account metadata, like `name` and `description`.

*Parameters*:

    * `account` (Object)
    ** `name` (String, optional) - account name
    ** `description` (String, optional) - account description
    ** `address` (String) - hex-encoded 20 bytes public address
    * `additional` (Object, optional)
    ** `chain` (String, optional) - chain name, by default `mainnet`, other possible variant `testnet`
    ** `chain_id` (Number, optional) - chain id number, by default for `mainnet` it equals `61`

*Result*: `accept` (Boolean) - `true` if required account exists

*Examples*:

.If required account exists
----
--> {"jsonrpc": "2.0", "method": "emerald_updateAccount", "params": [{"name": "new", "address": "0xe9a7e26bf5c05fe3bae272d4c940bd7158611ce9"}], "id": 1}
<-- {"jsonrpc": "2.0", "result": true, "id": 1}
----

.If required account doesn't exist
----
--> {"jsonrpc": "2.0", "method": "emerald_updateAccount", "params": [{"address": "0x3d80b31a78c30fc628f20b2c89d7ddbf6e53cedc"}], "id": 1}
<-- {"jsonrpc": "2.0", "error": {"code": -32000, "message": "Account doesn't exist"}, "id": "1"}
----

=== emerald_importAccount

Import a new account from an external keyfile.

*Parameters*:

    * `keyfile` (Object) - should be totally comply with the https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition[Web3 UTC / JSON format]
    * `additional` (Object, optional)
    ** `chain` (String, optional) - chain name, by default `mainnet`, other possible variant `testnet`
    ** `chain_id` (Number, optional) - chain id number, by default for `mainnet` it equals `61`

*Result*: `address` (String) - successfully imported hex-encoded 20 bytes public address

*Examples*:

----
--> {"jsonrpc": "2.0",
     "method": "emerald_importAccount",
     "params":
       [{"version": 3,
         "id": "f7ab2bfa-e336-4f45-a31f-beb3dd0689f3",
         "address": "0047201aed0b69875b24b614dda0270bcd9f11cc",
         "crypto": {
           "ciphertext": "c3dfc95ca91dce73fe8fc4ddbaed33bad522e04a6aa1af62bba2a0bb90092fa1",
           "cipherparams": {
             "iv": "9df1649dd1c50f2153917e3b9e7164e9"
           },
           "cipher": "aes-128-ctr",
           "kdf": "scrypt",
           "kdfparams": {
             "dklen": 32,
             "salt": "fd4acb81182a2c8fa959d180967b374277f2ccf2f7f401cb08d042cc785464b4",
             "n": 1024,
             "r": 8,
             "p": 1
           },
           "mac": "9f8a85347fd1a81f14b99f69e2b401d68fb48904efe6a66b357d8d1d61ab14e5"}}],
     "id": 1}
<-- {"jsonrpc": "2.0", "result": "0x0047201aed0b69875b24b614dda0270bcd9f11cc", "id": 1}
----

=== emerald_exportAccount

Returns an account keyfile associated with the account.

*Parameters*:

    * `account` (Object)
    ** `address` (String) - hex-encoded 20 bytes public address
    * `additional` (Object, optional)
    ** `chain` (String, optional) - chain name, by default `mainnet`, other possible variant `testnet`
    ** `chain_id` (Number, optional) - chain id number, by default for `mainnet` it equals `61`

*Result*: `keyfile` (Object) - account in https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition[Web3 UTC / JSON format]

*Examples*:

----
--> {"jsonrpc": "2.0", "method": "emerald_exportAccount", "params": [{"address": "0x0047201aed0b69875b24b614dda0270bcd9f11cc"}, {"chain_id": 62}], "id": 1}
<-- {"jsonrpc": "2.0",
     "result":
       [{"version": 3,
         "id": "f7ab2bfa-e336-4f45-a31f-beb3dd0689f3",
         "address": "0047201aed0b69875b24b614dda0270bcd9f11cc",
         "crypto": {
           "ciphertext": "c3dfc95ca91dce73fe8fc4ddbaed33bad522e04a6aa1af62bba2a0bb90092fa1",
           "cipherparams": {
             "iv": "9df1649dd1c50f2153917e3b9e7164e9"
           },
           "cipher": "aes-128-ctr",
           "kdf": "scrypt",
           "kdfparams": {
             "dklen": 32,
             "salt": "fd4acb81182a2c8fa959d180967b374277f2ccf2f7f401cb08d042cc785464b4",
             "n": 1024,
             "r": 8,
             "p": 1
           },
           "mac": "9f8a85347fd1a81f14b99f69e2b401d68fb48904efe6a66b357d8d1d61ab14e5"}}],
     "id": 1}
----

=== emerald_signTransaction

Signs transaction offline with private key from keystore file with given passphrase.

*Parameters*:

    * `transaction` (Object)
    ** `from` (String) - the address the transaction is sent from (hex-encoded 20 Bytes)
    ** `to` (String, optional when creating new contract) - the address the transaction is directed to (hex-encoded 20 Bytes)
    ** `gas` (String) - Hex-encoded integer of the gas provided for the transaction execution, it will return unused gas
    ** `gasPrice` (String) - Hex-encoded integer of the gasPrice used for each paid gas
    ** `value` (String, optional) - Hex-encoded integer of the value sent with this transaction
    ** `data` (String, optional) - The compiled code of a contract OR the hash of the invoked method signature and encoded parameters (smart contract ABI)
    ** `nonce` (String) - Hex-encoded integer of a nonce, this allows to overwrite your own pending transactions that use the same nonce
    ** `passphrase` (String) - passphrase used to encode keyfile
    * `additional` (Object, optional)
    ** `chain` (String, optional) - chain name, by default `mainnet`, other possible variant `testnet`
    ** `chain_id` (Number, optional) - chain id number, by default for `mainnet` it equals `61`

*Result*: `data` (String) - hex-encoded signed raw transaction data

*Examples*:

----
--> {"jsonrpc": "2.0",
     "method": "emerald_signTransaction",
     "params":
       [{"from": "0xb60e8dd61c5d32be8058bb8eb970870f07233155",
         "to": "0xd46e8dd67c5d32be8058bb8eb970870f07244567",
         "gas": "0x76c0",
         "gasPrice": "0x9184e72a000",
         "value": "0x9184e72a",
         "data": "0xd46e8dd67c5d32be8d46e8dd67c5d32be8058bb8eb970870f072445675058bb8eb970870f072445675",
         "nonce": "0x1000",
         "passphrase": 1234567890"},
        {"chain": "testnet"}],
     "id": 1}
<-- {"jsonrpc": "2.0", "result": "0xd46e8dd67c5d32be8d46e8dd67c5d32be8058bb8eb970870f072445675058bb8eb970870f072445675", "id": 1}
----

== Custom Errors

|===
|Code |Message |Meaning

|-32000
|Account doesn't exist
|Nothing is found at the specified account public address
|===
