name: Test

on:
  push:
    branches:
      - master
      - release/*
      - ci/*
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Test ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "windows-latest", "macos-latest", "ubuntu-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Instal system libs (Linux)
        run: sudo apt-get install libusb-1.0-0-dev
        if: runner.os == 'Linux'

      - name: Instal LLVM (Windows)
        run: choco install -y llvm
        if: runner.os == 'Windows'

      - name: Instal system libs (Windows)
        run: vcpkg install libusb
        if: runner.os == 'Windows'

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --release
        env:
          RUST_BACKTRACE: "1"

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --release
        env:
          RUST_BACKTRACE: "1"

  coverage:
    name: Coverage Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Instal system libs
        run: sudo apt-get install libusb-1.0-0-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'

      - name: Coverage Report
        id: coverage
        uses: actions-rs/grcov@v0.1

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ steps.coverage.outputs.report }}

      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ${{ steps.coverage.outputs.report }}
