name: Test

on:
  push:
    branches:
      - master
      - release/*
      - ci/*
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Test ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "windows-latest", "macos-latest", "ubuntu-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Instal system libs (Linux)
        run: sudo apt-get install libusb-1.0-0-dev
        if: runner.os == 'Linux'

      - name: Instal LLVM (Windows)
        run: choco install -y llvm
        if: runner.os == 'Windows'

      - name: Instal system libs (Windows)
        run: vcpkg install libusb
        if: runner.os == 'Windows'

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --release
        env:
          RUST_BACKTRACE: "1"

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --release
        env:
          RUST_BACKTRACE: "1"

  coverage:
    name: Coverage Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Instal system libs
        run: sudo apt-get install libusb-1.0-0-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      # https://github.com/xd009642/tarpaulin
      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Generate Code Coverage
        uses: actions-rs/cargo@v1
        with:
          command: tarpaulin
          args: --release --no-fail-fast --out Lcov --output-dir ./coverage
          # coverage report is in ./coverage/lcov.info and ./target/tarpaulin/emerald-vault-coverage.json

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
